# Generated by Django 5.0.14 on 2026-09-26 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SnapshotPolicy',
            fields=[
                ('id', models.IntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('auto_enabled', models.BooleanField(default=False)),
                ('auto_interval_minutes', models.IntegerField(default=30)),
                ('auto_scope', models.CharField(default='system', max_length=16)),
                ('keep_last', models.IntegerField(default=20)),
                ('keep_days', models.IntegerField(default=7)),
                ('auto_include_files', models.BooleanField(default=False)),
                ('last_auto_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'snapshot_policy',
            },
        ),
        migrations.CreateModel(
            name='SystemGate',
            fields=[
                ('id', models.IntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('RUNNING', 'RUNNING'), ('PAUSED', 'PAUSED'), ('RESTORING', 'RESTORING')], default='RUNNING', max_length=16)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('message', models.TextField(blank=True, default='')),
                ('operator_id', models.IntegerField(blank=True, null=True)),
                ('operator_name', models.CharField(blank=True, default='', max_length=128)),
                ('since', models.DateTimeField(blank=True, null=True)),
                ('ttl_seconds', models.IntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('active_snapshot_id', models.IntegerField(blank=True, null=True)),
                ('progress', models.CharField(blank=True, default='', max_length=255)),
                ('data_version', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'system_gate',
            },
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='快照名称（管理员可读）', max_length=128)),
                ('note', models.TextField(blank=True, default='', help_text='备注')),
                ('kind', models.CharField(choices=[('manual', 'manual'), ('auto', 'auto'), ('pre-restore', 'pre-restore'), ('system', 'system')], default='manual', max_length=16)),
                ('status', models.CharField(choices=[('building', 'building'), ('ready', 'ready'), ('failed', 'failed'), ('restoring', 'restoring'), ('restored', 'restored')], default='building', max_length=16)),
                ('scope', models.CharField(choices=[('competition', 'competition'), ('system', 'system')], default='competition', max_length=16)),
                ('competition_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('competition_name', models.CharField(blank=True, default='', max_length=128)),
                ('table_count', models.IntegerField(default=0)),
                ('row_count', models.BigIntegerField(default=0)),
                ('byte_size', models.BigIntegerField(default=0)),
                ('include_files', models.BooleanField(default=False)),
                ('file_count', models.IntegerField(default=0)),
                ('file_byte_size', models.BigIntegerField(default=0)),
                ('data_version', models.IntegerField(default=0)),
                ('server_seq', models.BigIntegerField(default=0)),
                ('app_version', models.CharField(blank=True, default='', max_length=32)),
                ('manifest_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('created_by_id', models.IntegerField(blank=True, null=True)),
                ('created_by_name', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duration_ms', models.IntegerField(default=0)),
                ('locked', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True, default='')),
                ('storage_path', models.CharField(blank=True, default='', max_length=255)),
                ('restore_count', models.IntegerField(default=0)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('last_restored_by_name', models.CharField(blank=True, default='', max_length=128)),
            ],
            options={
                'db_table': 'snapshots',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['competition_id', '-created_at'], name='snapshots_competi_d7787e_idx'), models.Index(fields=['status', '-created_at'], name='snapshots_status_9b4612_idx')],
            },
        ),
        migrations.CreateModel(
            name='SnapshotTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_label', models.CharField(help_text='如 materials.Material', max_length=64)),
                ('model_name', models.CharField(help_text='如 Material', max_length=64)),
                ('table_name', models.CharField(max_length=64)),
                ('resource', models.CharField(blank=True, default='', max_length=64)),
                ('policy', models.CharField(choices=[('full', 'full'), ('upsert', 'upsert'), ('record', 'record')], default='full', max_length=16)),
                ('row_count', models.BigIntegerField(default=0)),
                ('byte_size', models.BigIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('file_name', models.CharField(blank=True, default='', max_length=160)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='snapshots.snapshot')),
            ],
            options={
                'db_table': 'snapshot_tables',
                'ordering': ['id'],
                'unique_together': {('snapshot', 'table_name')},
            },
        ),
    ]
